### PR TITLE
sprint4-2-HomePageResourcesBanner-KW

### PR DESCRIPTION
**Pull request by wessstt**
1. Added resources banner to home page with quick links that link out to
    - search dogs
    - search cats
    - contact 
    - resources page
2. Compressed pet images to help the speed. 
3. Revised Navbar error. 
4. Added Icons for the Resources quick links. 
5. Moved Icons to new folder.
6. Revised Imports on App.jsx (_had some duplicates from merge conflict_)

### CODE REVIEW

**Comment by shreeup** [comment]
i thinks resource page is missing header and footer, other than that i didnot see any major issue

**Review by shreeup — APPROVED** [review]

**Review by Count-MonteCristo — CHANGES_REQUESTED** [review]
Overall, the changes look great! I just have a couple of suggestions:

1. As @shreeup pointed out, the resource page is missing the header and footer. These two should be present on every page.
2. On the resource banner for the home page, it's not clear where the user has to press to go to the resource. There are a couple of ways you could go about addressing this issue:
- Change the mouse cursor to a pointer on hover using CSS
- Make the whole card clickable. You can pair this with making the background color of the card change colors on hover as well.
- Add a magnification animation to either the resource icon or the card.

Besides that, everything else looks/works great!

**Comment by wessstt** [comment]
Thanks y'all. I added updates to the quick links to include the mouse pointer change on hover and made the entire card clickable. Thanks for the comments that was an over sight on my end. 😵‍💫. 

I also added an update to the pet profile page. I made the Start adoption button take the user to the contact form.

**Comment by divinedouggy** [comment]
I have the Header and Footer on the Resources Page on my working branch.

**Comment by wessstt** [comment]
> I have the Header and Footer on the Resources Page on my working branch.

I figured, I did not touch it since you're working on it. :)

**Review by Count-MonteCristo — APPROVED** [review]

**Pull request merged**
