### PR TITLE
Contactus

### PR DESCRIPTION
**Pull request by shreeup**
https://github.com/Code-the-Dream-School/ffprac-team3-front/assets/16798480/b26d2eb8-950b-40c6-8134-10b7fb1d112c

### CODE REVIEW

**Review by Leonardo-Reyes-Munoz — APPROVED** [review]
Changes look Shree. I was able to also run and submit an email which then was received by our shared email box. 

I appreciated the video walk through as well! 

I will add a request for Luis or Chase to review as they have time as well since they would prefer that we have at least one mentor review before merging.

**Review by wessstt — APPROVED** [review]
Looks good. Great feature to make it feel legit.
Should we add the navbar and footer so that the user can navigate back to the site after submission?

**Review by Count-MonteCristo — APPROVED** [review]
Love it! Make sure to showcase this during your presentation - Great job!

**Comment by shreeup** [comment]
made changes as suggested in review

**Pull request merged**
